name: Pre-prod-CI 

on:
  push:
  
jobs:
 Build-Push-To-GCR:

#choose the OS in which you want to trigger the job 

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
